spring.application.name=irctc-App

spring.datasource.url=jdbc:mysql://localhost:3306/irctc-app
spring.datasource.username=root
spring.datasource.password=root12

spring.jpa.hibernate.ddl-auto=update

