spring.application.name=15-Data-JPA-OneToOne-App


spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/sbms
spring.datasource.username=root
spring.datasource.password = root12

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true