spring.application.name=Rest-Api-App-02

spring.datasource.url=jdbc:mysql://localhost:3306/restapp2
spring.datasource.username=root
spring.datasource.password=root12
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update