spring.application.name=20-Web-MVC-Form-App-1


spring.datasource.url=jdbc:mysql://localhost:3306/mvcpract
spring.datasource.username=root
spring.datasource.password=root12

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.mvc.view.prefix=/views/
spring.mvc.view.suffix=.jsp